### ISSUE TITLE
feature request: buffer management adapter

### ISSUE THREAD

**Issue by davidsierradz** [stevearc/oil.nvim#118]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Could we leverage oil adapter API to write a buffer management meta-buffer similar to the current one with files, I don't know if all the primitives are exposed to manage buffers with this meta-buffer (?). For example, `:ls`, `:badd`, `:bdelete`, `:bwipeout`, `:bunload`, `:sbuffer`, etc.

Makes sense? Something like [A simple plugin to easily manage Neovim buffers.](https://github.com/j-morano/buffer_manager.nvim)

Thanks!

**Comment by stevearc** [comment]
This is a very interesting idea, and I think it should be technically possible. It's a little wonky because the (two existing) adapters have the ability to interop. Meaning you can copy or move files between your local system and ssh, but it's not obvious how that would work with buffers (especially non-file buffers). I think that's a small barrier, though, and I'm not overly worried about blocking interop between a buffer view and other adapters.

I don't have the time to play around with this at the moment, but I would happily review a PR!

**Comment by dvjn** [comment]
I had the same idea, came here to suggest it, and stumbled upon this issue.

I would love to write a PR for this, but I am having some difficulties in understanding how to start writing a new adapter. For me, "adapters/test.lua" is too barebones to understand what is expected out of each function, and "adapters/files.lua" has too much happening which makes it difficult for me to dissect it.

Any starting point or even one-liner function descriptions in "adapers/test.lua" would help :)

**Comment by stevearc** [comment]
I did some refactoring to fix the type annotations, add some comments, and also make it easier to implement an adapter. I'm still viewing the adapter API as "wet paint", but it's at least _more_ ready to build on top of.

I also took a stab at a basic implementation, which you can see in the linked PR. Feel free to play with it, but it has some pretty significant limitations at the moment. It was a neat idea to explore, but I came out of it more convinced that this isn't a domain that oil is well suited for. I could probably write a standalone plugin with the same or better features and less complexity than what it would add to oil.
