### ISSUE TITLE
allow changing file name

### ISSUE THREAD

**Issue by max397574** [stevearc/oil.nvim#12]
![image](https://user-images.githubusercontent.com/81827001/210511048-db8a0e8b-e58d-4f93-8bd4-8e5986b50318.png)

I'd like to be able to just have `~/.config/neovim_configs/omega/` here

I don't know why the `oil://` is there
but the `~` could be done with `fnamemodify` (`:~`)

**Comment by max397574** [comment]
perhaps you could expose a hook function which is called on the filename
so users could do whatever they want

**Comment by stevearc** [comment]
Done! It was displaying `oil://` because that's part of the full buffer name, and the title was just displaying the buffer name. I added a special case for the files adapter to display the title as the file path instead; other adapters will still show the full url.

I'd like to try to avoid adding config options unless I absolutely have to. I took a lot of requests and PRs that added options for another of my plugins, and it grew to be kind of a mess :/
