### ISSUE TITLE
feature request: Git/User extensible file manipulation

### ISSUE THREAD

**Issue by jonathf** [stevearc/oil.nvim#124]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Allow oil operations to also be git operations.
in other words when you applying changes; the changes are done through git.

Adding this feature doesn't really have to be git specific. infact, it would be neat if it were more general using either callbacks or adapter system for atomic operations like `mv`, `cp`, `rm`, etc. and let the user figure out the rest.

### Provide background

Most operations I do is inside git folders, and using oil would be much more usefule if I could somehow let it do git operations associated with the operation of interest.

**Comment by stevearc** [comment]
This would add a whole lot of complexity, because now every operation has to be aware of the git status of each entry and potentially fall back to a different operation. You can't `git mv` a file that isn't tracked, for example. It's also unclear when adding or moving tracked files into a gitignored directory...should they still be tracked? Is this a `git rm` and we expect them to be local ignored files now? If you delete a file, is that a `git rm`, or should it do a full `git rm -f`?

Filesystems are hard. Git is hard. Trying to do both at the same time in a coherent way is beyond my abilities. I would love for someone to prove me wrong and show me a simple way to make this behave intuitively, but for now I'm closing this as out of scope.
