### ISSUE TITLE
feature request: remember location when viewing symlink

### ISSUE THREAD

**Issue by stejcon** [stevearc/oil.nvim#140]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

If you have an symlink in the current folder, follow that symlink, then use the go to parent function, you should be returned to your projects directory with the symlink, not to the directory of the actual resource.

### Provide background

I'm not sure if there's already a way to do this or if it is too compilcated to implement. I'm using nix for a couple of projects, and whenever I build a project the result appears as a symlink to the actual result which is stored in the nix store. Then whenever I use oil to go into the result and then use go to parent directory I end up in the nix store instead of the project folder. Is it possible to have go to parent directory of the symlink you used instead of the location of the actual file/folder? Also I'm not sure if "go to parent" is then the right term to use but maybe it could exist as a second function in addition to go to parent?

**Comment by stevearc** [comment]
You can actually already achieve this behavior using built-in vim functions! Since you're just navigating through normal buffers, if you want to return to the _previous_ buffer (instead of opening the _parent_ buffer), you can use the jumplist (`:help jumplist`). The default keymaps are `CTRL-O` to go backwards through the jumplist, and `CTRL-I` to go forwards.

**Comment by finnove** [comment]
Thanks. ctrl-o was a nice workaround. Agree with the feature request. The expected behavior for me is to go back to the previous page. Suggesting an update if possible (or option if this must be preserved). I recently did a setting in my terminal to fix this for the command line. now I can cd in and out of symlinks as expected. Dont remember if that was mac or ubuntu.
