### ISSUE TITLE
feature request: Interaction with Lualine

### ISSUE THREAD

**Issue by bradlauder** [stevearc/oil.nvim#144]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Hello, big fan so far!

I'm new to neovim. Wondering if it would be possible to get the same lualine functionality as when a file is open?

As of right now the git branch section of my lualine disappears inside oil. And also the filename section shows oil://... and it would be nice to have it follow the same pattern configure by lualine (relative, absolute) like netrw does.

![image](https://github.com/stevearc/oil.nvim/assets/130588075/5f791039-75b5-4c41-b58f-09d098c902a9)
![image](https://github.com/stevearc/oil.nvim/assets/130588075/4fabf914-76a0-43f3-b09e-54cb66db9b2f)

**Comment by stevearc** [comment]
This is something that would have to be addressed within lualine. Those components are built to check for the directory of the current file, but an oil buffer doesn't have an associated file (and has a url-formatted name like `oil:///home/user/`). We have chosen to name the buffers this way (instead of the raw directory name like `/home/user/`) in order to play nice with other file managers. If there is interest, the lualine components could be fairly easily modded to support this by adding a special-case check like
```lua
-- Assuming the component gets the current path something like this
local current_file = vim.api.nvim_buf_get_name(0)
-- If this is an oil buffer, use the API to get the current path
if vim.b.filetype == "oil" then
  current_file = require("oil").get_current_dir()
end
```
