### ISSUE TITLE
feature request: Add more highlight groups

### ISSUE THREAD

**Issue by Bekaboo** [stevearc/oil.nvim#212]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Add hlgroups for `permissions`, `size`, `mtime` etc in oil buffer.

### Provide background

Firstly thanks for making this plugin! For me oil is by far the best file manager in nvim -- it follows the "vim way" and is super intuitive.

I personally like Emacs' dired style of listing files and directories, so I set up oil like this:

```lua
require('oil').setup({
  columns = {
    'permissions',
    'size',
    'mtime',
    {
      'icon',
      default_file = ...,
      directory = ...,
    },
  },
})
```

the result is quite close but not as colorful as dired:

![image](https://github.com/stevearc/oil.nvim/assets/76579810/e9f00edd-62ef-4447-944d-063aa7199182)

I searched for hlgroups and find that there is no hlgroup defined for permissions, size and mtime.

Could we add such hlgroups to make oil buffer more colorful?

**Comment by stevearc** [comment]
If you check out `:help oil-columns`, you'll see that the columns have configuration options that you can pass to them. One option that is present on every column is `highlight`. You can use this to set special highlight groups for certain columns. For example:

```lua
require('oil').setup({
  columns = {
    'permissions',
    { 'size', highlight = "DiagnosticError" },
    { 'mtime', highlight = "Special" },
    {
      'icon',
      default_file = ...,
      directory = ...,
    },
  },
})
```

**Comment by Bekaboo** [comment]
Thanks, that makes it more colorful. However I find it still impossible to show different permissions in different colors. Could we add dedicated highlights for different permissions?

![Screenshot_20231102_162208](https://github.com/stevearc/oil.nvim/assets/76579810/a677c096-5a7d-4862-b08b-2b944901b0cd)

**Comment by stevearc** [comment]
Oil doesn't currently support multiple highlight groups within a column. We could theoretically add support for that by returning an array of `{ text, highlight }` chunks from the highlight function instead of just a highlight name.

This is a low priority for me, and given how little time I have and how many issues are in my backlog, I will probably never get to it. If you're interested in doing the refactor, I'd be willing to review the PR. Relevant code is

https://github.com/stevearc/oil.nvim/blob/aea896a880e294c97a7c395dd8a6c89bdc93c644/lua/oil/columns.lua#L137
and
https://github.com/stevearc/oil.nvim/blob/aea896a880e294c97a7c395dd8a6c89bdc93c644/lua/oil/view.lua#L516-L520

**Comment by Bekaboo** [comment]
I understand, thanks
