### ISSUE TITLE
feature request: :wq

### ISSUE THREAD

**Issue by arutonee1** [stevearc/oil.nvim#221]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

`:wq` currently behaves like `:w`. If the command was successful (the user presses `[O]k`), `:wq` should close Neovim as well.

### Provide background

I genuinely might see myself using oil.nvim as a file manager replacement, and this would save a lot of time for quick operations.

**Comment by stevearc** [comment]
I added support for this. It's a bit of a hack, but it seems to work well enough. I'm a _little_ concerned that there may be some unintended edge cases, so there's a chance I'll have to tweak this or roll it back.

**Comment by collindutter** [comment]
I'm running into an edge case of this change that causes Neovim to close unexpectedly. 

I have the following keymaps:
`vim.keymap.set('n', '<leader>w', '<CMD>w<CR>', {})`
`vim.keymap.set('n', '-', '<CMD>Oil<CR>', {})`

To reproduce:
1. Open Neovim.
2. Close Neovim with `:x`.
3. Open Neovim.
4. Open Oil with `-` keymap.
5. Create a file.
6. Save the buffer with `<leader>w` keymap.
7. Neovim closes.

This happens because commands run through keymaps are not inserted into the history table so the last command is still `:x`. 

Thanks for all the work you do!

**Comment by christianjuth** [comment]
I'm using LunarVim and the default <leader>w doesn't play nice with oil. However, I found overwriting the default <leader>w fixes it.

```
vim.api.nvim_del_keymap('n', '<leader>w')
vim.api.nvim_set_keymap('n', '<leader>w', ':w<CR>', { noremap = true, silent = true })
```
