### ISSUE TITLE
bug: oil.nvim sometimes fails to open when running `:edit %:p:h`

### ISSUE THREAD

**Issue by BojanStipic** [stevearc/oil.nvim#25]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

ArchLinux

### Describe the bug

If you open a file in nvim and soon after that run `:edit %:p:h`, oil.nvim sometimes fails to open. If you wait a few seconds and try again, it does open eventually.

If you run `:Oil` instead, it works correctly every time.

### Steps To Reproduce

1. `nvim some_file.txt`
2. run `:edit %:p:h`
3. _oil.nvim fails to open (nothing happens, there are no errors either)_
4. wait a few seconds
5. run `:edit %:p:h` again
6. _oil.nvim loads correctly_

### Expected Behavior

oil.nvim should always load when running `:edit %:p:h`.

### Directory structure

```bash
echo 'an example text file' > some_file.txt
```

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require"oil".setup() -- add any needed settings here
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
I can't get this to reproduce, but it sounds like a lazy loading issue. Are you doing any kind of lazy loading oil? It needs to create some autocmds when vim starts up to properly hook into things like `:edit %:p:h`.

Does this happen for you when using the minimal init.lua file listed above?

**Comment by BojanStipic** [comment]
No, I don't do any lazy loading in my config. Here is my current [init.lua](https://github.com/BojanStipic/dotfiles/blob/master/neovim/.config/nvim/init.lua). But anyway, I can reproduce the issue using the minimal `init.lua` listed above.

You just have to run `:edit %:p:h` really fast, immediately after opening a file. You can try either:
* using up arrow to bring up the last command and executing it soon as possible
* or binding it to a mapping like this: `vim.keymap.set('n', '-', '<cmd>edit %:p:h<cr>')` so it is easier to run quickly

It can be reproduced every time you repeat these steps, so as I understand it the issue should not be with lazy loading, as the plugin is clearly already loaded.

I am attaching a screencast to better demonstrate what I am doing:
[Screencast from 2023-01-11 01-02-42.webm](https://user-images.githubusercontent.com/13490088/211688243-66e4832d-048c-4ed8-b7c8-fba08887ff70.webm)

Thank you for your time and thank you for this amazing plugin!

**Comment by stevearc** [comment]
Ah, thanks for the recording! Made it a lot easier to reproduce the problem. This was some wacky interactions with the directory hijacking, stemming from how we're renaming buffers (from `/tmp` to `oil:///tmp`, for example). If the desired buffer name isn't in use yet, the rename is easy and it works fine. If it _does_ exist, then we have to delete the source buffer and replace it with the existing one (there's no way to effectively "merge" the buffers). We were doing that replacement synchronously during the BufAdd autocmd, and it was causing the `:edit` command to silently fail to do anything. I've fixed this by deferring the actual replacement operation so vim can complete the `:edit` before swapping the buffers.

The reason for the two second window where the command wouldn't work is because we wait 2 seconds after BufHide to clean up oil buffers. A more consistent way to see the problem is to open a vsplit and do `:edit %:p:h`. Any successive calls to `:edit %:p:h` in the other window will fail (or would, before this fix).
