### ISSUE TITLE
feature request: remove netrw dependency

### ISSUE THREAD

**Issue by nat-418** [stevearc/oil.nvim#27]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It would be nice to completely disable netrw and use oil as a replacement, including for remote SSH/SCP operations.

### Provide background

Netrw is buggy.

### Additional details

I have written a small plugin called scamp.nvim that does this, and several others exist like netman. Happy to help if this interests you.

**Comment by max397574** [comment]
I have netrw disabled and it works for me

**Comment by nat-418** [comment]
> I have netrw disabled and it works for me

According to the README, it is required: ![image](https://user-images.githubusercontent.com/93013864/211604827-7f62f3ae-dcc3-460c-87bc-f86ddedb158f.jpeg)

**Comment by stevearc** [comment]
The only thing oil relies on netrw for is editing files in the format `scp://servername/path/to/file.txt`. If you have some other way of doing that (looks like that's what scamp.nvim does), then it should just work.

Two things that do not work with scamp from my tests:
1. scamp requires the username to be present in the url or it will throw an error
2. scamp changes the buffer name from `scp://*` to `/tmp/*`. That means that once you open a remote file, you can't browse the parent directory with `oil.open()`. 

If you can fix these then I'll add a note in the README that scamp.nvim can be used as an alternative to netrw.

I may build this functionality directly into oil.nvim in the future, or switch it up to rely on netman. Undecided as of yet.

**Comment by stevearc** [comment]
I've added builtin support for file editing via scp. Netrw is no longer required

**Comment by nat-418** [comment]
Doesn't work in my testing. Just get "Unknown SSH Error"

**Comment by sassanh** [comment]
Sharing my observation: I ran `:e scp://<username>@<server>/<cr>` and it worked, I disabled netrw and removed scamp.nvim before running this command.

**Comment by miversen33** [comment]
Just chiming in here, removing netrw wont break this plugin but it _will_ break other features in vim. I would advise documenting this if you are recommending users disable netrw.

Examples of things that break when you disable netrw

- tar/zip browsing
- rsync browsing
- webdav browsing
- local filesystem browsing (with native vim, most third party plugins do not require netrw to function).

**Comment by sassanh** [comment]
@miversen33 I think there is a misunderstanding here. This is for those who already disabled netrw. For example I always disliked netrw and actively searched to find a way to disable it in Neovim long ago and intentionally disabled it. So I was bothered that I should bring it back to activate ssh feature of oil and now I'm happy I can keep it disabled and use `scp://` schema.

I mean whether to use or not use netrw is a personal decision and beyond the scope of this plugin I think, it is not a requirement of using oil as far as I understand.

**Comment by miversen33** [comment]
@sassanh  that is incorrect, [oil.nvim does indeed disable netrw](https://github.com/stevearc/oil.nvim/blob/ca4da68aaebaebf5cd68151c2b5ad56e00c06126/lua/oil/init.lua#L606-L608). And that is fine, I am simply stating that by doing so, there are side effects that the developer (@stevearc) may not have been aware of. I dove into this a bit [in my own plugin](https://github.com/miversen33/netman.nvim/issues/41) where I uncovered some consequences of disabling netrw (the ones I listed above and more). Netrw is sadly, quite engrained in vim core unfortunately, alot of things rely on it. 

Disabling it is fine, but it should probably be called out somewhere in the readme (or help doc would probably be better) that there can be some side effects for disabling netrw, which this plugin does.

**Comment by sassanh** [comment]
You are right, this is new in ssh support commit.
Yes I agree with you that it's better to be either optional (default off) or mentioned explicitly somewhere.

**Comment by sassanh** [comment]
And if we disable `netrw`, shouldn't we also disable `netrwSettings`, `netrwFileHandlers` just like `netrwPlugin`?

**Comment by miversen33** [comment]
Its been a while since I have dove into netrw, but I seem to recall that the later variables (`netrwSettings` and `netrwFileHandlers`) are not set (and thus null/0/whatever tf vimscript considers "falsey") by default. IE, because netrw short circuits if `loaded_netrwPlugin` and `loaded_netrw` are already set, it just returns, assuming its work is already done. Basically, setting those flags is a abusing the general practice of vimscript plugins where they check global state variables to see if they need to initialize themselves, as they may have already done so. 

I don't believe setting those flags will hurt anything, though I don't believe they are necessary to "prevent" netrw from hijacking `uri` reads (via preventing it from setting its aucommands).

**Comment by sassanh** [comment]
I see, but even If those two don't hijack uri, there is still benefit in disabling them: By turning off `netrw` and `netrwPlugin` we are probably making the other two obsolete and most users probably won't know about it to disable them themselves and get the startup time benefit.

**Comment by nat-418** [comment]
my two cents:

1. Oil is shaping up to replace netrw _for me_. I wish we could either fix netrw to be less broken or somehow replace it in Neovim altogether. Oil right now is the next best thing _for my use case_.

2. I personally do not think disabling netrw should be automagic. It should be documented in the README / :help as a recommended configuration option. But Oil _is not my baby_, so I respect whichever way the maintainer chooses to go.

**Comment by max397574** [comment]
imo netrw definitely shouldn't be disabled if it's somehow avoidable
if it isn't it should be written with a disclaimer in the readme @stevearc

**Comment by stevearc** [comment]
@miversen33 you are correct, I was under the impression that netrw only handled local and ssh file browsing, but I see it's also handling [rsync, ftp, http, etc](https://github.com/neovim/neovim/blob/6e3890f4ce002ba308c09166b00e8ee86b6efa03/runtime/plugin/netrwPlugin.vim#L46-L49). I'm confused that you mentioned tar/zip browsing, because it looks like those are handled by separate [tarPlugin.vim](https://github.com/neovim/neovim/blob/master/runtime/plugin/tarPlugin.vim), [gzip.vim](https://github.com/neovim/neovim/blob/master/runtime/plugin/gzip.vim), and [zipPlugin.vim](https://github.com/neovim/neovim/blob/master/runtime/plugin/zipPlugin.vim) files. I did some simple tests and they seem to function even with netrw disabled.

I think the correct thing to do is to change the ssh editing scheme back to something that doesn't conflict (`scp://` -> `oil-ssh://`). Unfortunately, that will produce some thrash since I _just_ changed that scheme, but I can add some affordances to make it a bit easier to notice and migrate. I really hate doing anything backwards-incompatible, but I think this has to be done. Once the url schemes don't overlap with netrw, then the user can disable it or not at their leisure.

I'll remove the auto-disabling logic and leave a note in the README about how one can disable netrw.

@nat-418 with respect to the "Unknown SSH Error", I added some more details to that notification that should help you investigate a bit. Basically, the ssh process we're spawning (which we do even if you're editing a file and not a directory) is failing with a nonzero exit code. If you run `:lua require("oil.adapters.ssh").open_terminal()` you should be able to see the command output; hopefully it'll have some clues as to why it failed.

**Comment by nat-418** [comment]
> @miversen33 you are correct, I was under the impression that netrw only handled local and ssh file browsing, but I see it's also handling [rsync, ftp, http, etc](https://github.com/neovim/neovim/blob/6e3890f4ce002ba308c09166b00e8ee86b6efa03/runtime/plugin/netrwPlugin.vim#L46-L49). I'm confused that you mentioned tar/zip browsing, because it looks like those are handled by separate [tarPlugin.vim](https://github.com/neovim/neovim/blob/master/runtime/plugin/tarPlugin.vim), [gzip.vim](https://github.com/neovim/neovim/blob/master/runtime/plugin/gzip.vim), and [zipPlugin.vim](https://github.com/neovim/neovim/blob/master/runtime/plugin/zipPlugin.vim) files. I did some simple tests and they seem to function even with netrw disabled.
> 
> I think the correct thing to do is to change the ssh editing scheme back to something that doesn't conflict (`scp://` -> `oil-ssh://`). Unfortunately, that will produce some thrash since I _just_ changed that scheme, but I can add some affordances to make it a bit easier to notice and migrate. I really hate doing anything backwards-incompatible, but I think this has to be done. Once the url schemes don't overlap with netrw, then the user can disable it or not at their leisure.
> 
> I'll remove the auto-disabling logic and leave a note in the README about how one can disable netrw.
> 
> @nat-418 with respect to the "Unknown SSH Error", I added some more details to that notification that should help you investigate a bit. Basically, the ssh process we're spawning (which we do even if you're editing a file and not a directory) is failing with a nonzero exit code. If you run `:lua require("oil.adapters.ssh").open_terminal()` you should be able to see the command output; hopefully it'll have some clues as to why it failed.

You could also just keep the ssh:// scheme and put it behind a feature flag like `replace_netrw` or something.



> Sharing my observation: I ran `:e scp://<username>@<server>/<cr>` and it worked, I disabled netrw and removed scamp.nvim before running this command.

This does not work for me on the latest HEAD

**Comment by miversen33** [comment]
@stevearc After looking back through netrw source it is [remote compressed files](https://github.com/neovim/neovim/blob/af82eab946cf9f36e544b0591b8c8c02e8ddf316/runtime/autoload/netrw.vim#L2424-L2429) it allows browsing of, not local. My mistake, its been a hot minute since I dug into the netrw source lol.

I have edited my above comment to reflect :)

Potentially another way to handle this is with some good ole "Hackity Schmakity".
Something I have been thinking about (but haven't tried yet) is auto overriding the `ssh` rules in the `netrw` augroup (or rather stripping them out altogether). You could in theory do this by setting an aucommand on the `UIEnter` event that checks to see if whatever your `augroup` is exists, and if it does, it auto rewrites the autocommands for `netrw`, stripping out whatever adapters you overwrite (such as `ssh`).

Unfortunately you can't just remove them on init of the plugin as it _seems_ that the vimcore plugins are triggered _during_ the load of lua plugins, thus you end up in a race condition of sometimes you can see the netrw augroup exists and other times you dont. 

If however, you abuse the `UIEnter` event, you might be able to quickly do the above rewrite (which should in theory be "instant", especially if you pregenerate what the new command should look like during the init of `oil.nvim`).

Its awfully disgusting but might allow both netrw and this to coincide. Its an avenue I plan on exploring more when I get done dicking with async stuff in netman, but if you are feeling [extra adventerous](https://www.reddit.com/r/itsaunixsystem/comments/34u94g/ski_mask_essential_gear_for_every_hacker/), it might be worth a try, if you want to get netrw and oil.nvim to live together relatively peacefully

**Comment by sassanh** [comment]
We need to take care of running vim with an argument starting with `scp://` too. I think `BufEnter` and `FileReadPost` run before `UIEnter`, it shouldn't be hard to handle though.
Can we use `VimEnter` instead of `UIEnter`? I'm not sure "ui" will be entered when Neovim is running embedded, not sure.

**Comment by miversen33** [comment]
All good points and I will not atest to either idea working, it's just a theory I have in my head at this time. The main idea is, find an event that fires after vim is loaded but before buffers begin rendering. VimEnter may be it, I don't know for sure :)

**Comment by stevearc** [comment]
@miversen33 that's a neat idea, and I definitely think it could be made to work. I'm personally hesitant to add that amount of coupling and hacky magic unless is absolutely necessary, and I'm not yet convinced that it is. Conflicts should only ever be seen by people that for some reason want both oil.nvim and netrw to be active, and even then they mostly coexist now that I changed the scheme back to `oil-ssh://`. If someone writes in really needing this I'd consider it, but more likely I'd come up with a snippet they could put in their own config instead of including it in oil directly.
