### ISSUE TITLE
bug: Malformed ID at start of line

### ISSUE THREAD

**Issue by angelidis** [stevearc/oil.nvim#272]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Windows 11

### Describe the bug

i love this plugin, thank you for all the work you've put into it -- here is a potential bug i found:

plugins fails to rename substitute spaces for dashes

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

step1: assume folder contents:

```
test me 1.md
test me 2.md
test me 3.md
test me 4.md
```
and an oil.nvim buffer without icons or anything else displayed apart from the filenames

step 2:

try to change from spaces (" ") to dashes ("-"):
```:'<,'>s/ /-/g```

you get the error: Malformed ID at start of line

### Expected Behavior

```
test-me-1.md
test-me-2.md
test-me-3.md
test-me-4.md
```

### Directory structure

```
test me 1.md
test me 2.md
test me 3.md
test me 4.md
```

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({
              -- add any needed settings here
            })
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment]
Yes this is unfortunately the Big Hack that makes this plugin work leaking out. There's more than just the filenames in this buffer: each one of them is prefixed with a unique ID. This is how we track file moves and renames. They're concealed by default because they just add visual clutter, but they _are_ still there and that means if you do whole-file edits like this it messes them up. You can see what's actually going on by doing `:set conceallevel=0`

Unfortunately, there's no good way to prevent this in the plugin. The most I can offer is try doing these things via visual block mode instead of normal visual mode to avoid mutating the IDs.

**Comment by angelidis** [comment]
makes perfect sense, appreciate the detailed explanation.

cheers!
