### ISSUE TITLE
feature request: Columns after filename

### ISSUE THREAD

**Issue by ArjunSahlot** [stevearc/oil.nvim#281]
### Did you check existing requests?

- [x] I have searched the existing issues

### Describe the feature

Make it possible to place column information after the filename.

### Provide background

First of all, I absolutely love this plugin and am disappointed I didn't find it earlier. Truly helps me a lot.

I was interested in using the columns feature but I've noticed they always come before the filename, and there is no functionality to move them after. Although I do acknowledge this format matches `ls` better, my eyes are conditioned to look right at the start of the line from `netrw`; so having this option would be amazing.

### What is the significance of this feature?

nice to have

### Additional details

One way to implement this would be to make the "name" column placeable in the options.

**Comment by stevearc** [comment]
Unfortunately this customization is impossible for oil. Because of how oil works, each line that gets rendered must also be _parseable_ so that we can read back changes. Columns can each define how they get parsed, so it allows for fairly flexible formats (e.g. a single column can contain whitespace), but there is an issue with filenames. Filenames can be...anything. They can contain whitespace, or not, special characters, or not, and there's no way to look at a sequence of characters and determine when a filename has ended and something else has begun. For this reason, the filename _must_ be located at the end of the line so that we can parse all of the values with known formats (columns) first, and then take the rest of the line as the filename.

**Comment by ArjunSahlot** [comment]
Thanks for a descriptive reply, I can definitely see you have thought about this before. Just for my satisfaction, I'd like to ask if it's possible to do this if you check for columns backwards; perhaps a setting like this:
```lua
columns = {
    "icon",
    "permissions",
    "size",
    "mtime",
    reverse = true,
  },
```

or maybe
```lua
...
columns = {
    "icon",
    "permissions",
    "size",
    "mtime",
  },
reverse_columns = true,
...
```

**Comment by stevearc** [comment]
Technically possible, but would add more complexity to the code than I think it's worth. Also doesn't play nice with some of the other mechanisms such as using `<filename> -> <destination>` for symbolic links and using virtual text for other information (e.g. original location of a trashed file)
