### ISSUE TITLE
feature request: Option to enable Oil (netrw) buffer as an alternate buffer

### ISSUE THREAD

**Issue by mynamedjef** [stevearc/oil.nvim#284]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Enable Oil buffer as an alternate file until cleanup period expires (or until another file is set as an alternate). So using `<C-^>` rapidly will switch between Oil buffer and buffer of a file from which Oil was invoked.

### Provide background

Example workflow:
1. I'm writing something in an ordinary file buffer.
2. I click (i.e.) `-` to invoke Oil. I scroll throughout Oil buffer, but I remember I have to go back to take a look at the file I just edited for a second.
3. I use `<C-^>` to go back since it is an alternate file (that way I don't have to search for it in Oil).
4. I finish looking what I wanted, so now I have to return to Oil buffer.
5. But, I can't use `<C-^>` again since Oil buffer is not set as an alternative buffer, which forces me to use `-`.
 
So I have to make mental note that when I'm in Oil buffer I have to use `<C-^>` to go back and when I'm in ordinary file buffer I have to use `-` to switch to Oil.
This pattern (spamming `<C-^>` to switch between alternates) is ingrained in my brain and is a frequent and intended vim workflow. It would be really nice if Oil also followed that principle.

Additional inconvenience comes if original buffer has an alternate file, so doing `<C-^>` in Oil returns you to original buffer, but doing `<C-^>` again returns you to its alternate file, not Oil. So it not only doesn't do what you want but confuses you more.

### What is the significance of this feature?

nice to have

### Additional details

I understand that this might be rendered redundant by `<C-o>` `<C-i>`.

**Comment by stevearc** [comment]
The problem is this is very much a matter of personal preference and also the situation you are in. Right now you have a situation where you want to set the oil buffer as an alternate after leaving. In a different situation maybe you open oil, then realize you don't want to be there and return to your original file. If you don't intend to return to oil, wouldn't you want your alternate buffer to be the original alternate buffer before opening oil?

I don't think that there's a way to have the ideal behavior, because there's no way to capture the intent as you leave oil. Indeed, sometimes when I'm using oil I don't yet know if I'm going to want to return after I leave. Given that, I think that the best we can do is try to have very _consistent_ behavior. We aim to make it so that oil buffers never appear as the alternate buffer, so at least it's predictable.

For your use case, I'd recommend one of the other mechanisms for jumping back into oil. Either re-opening it with `:Oil` or using the jumplist `<C-o>`.
