### ISSUE TITLE
bug: oil.nvim doesn't play well with sessions

### ISSUE THREAD

**Issue by heygarrett** [stevearc/oil.nvim#29]
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

```
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info
```

### Operating system/version

macOS 13.1

### Describe the bug

Oil buffers saved in a session are not able to be reopened by Neovim when that session is restored. Instead the following message is displayed (`~/.config/nvim` was the directory open in the oil buffer):

```
"oil:///Users/garrett/.config/nvim/" [Not edited] --No lines in buffer--
```

### Steps To Reproduce

1. `nvim -u repro.lua`
2. `:Oil`
3. `:mksession!`
4. `:q`
5. `nvim -u repro.lua`
6. `:source Session.vim`

### Expected Behavior

The oil buffer that was open before quitting Neovim would reopen.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require"oil".setup() -- add any needed settings here
        end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by stevearc** [comment]
Confirmed, I can reproduce this. For whatever reason, `mksession` restores oil buffers using `:file` instead of `:edit` (maybe because the buftype is acwrite).
```vim
badd +0 oil:///private/tmp/
argglobal
%argdel
$argadd oil:///private/tmp/
argglobal
enew
file oil:///private/tmp/
```
As opposed to a normal file
```vim
badd +0 test.txt
argglobal
%argdel
$argadd test.txt
edit test.txt
```

Unfortunately this is terrible because we rely on autocmds to tell us when to load a buffer. What happens is that the session does a `badd` which triggers `BufAdd`. Then the `enew` doesn't trigger anything for us. Then the `:file` command _also_ doesn't fire any autocmds. There's no BufReadCmd, not even a BufLoad or BufEnter for the oil buffer (verified by running the commands manually with `set verbose=9`).

The workaround I've applied is to listen to the `SessionLoadPost` autocmd and manually go through all buffers. If we find any empty oil buffers, we manually call the load function for them. Feels like a hack, but I couldn't think of a better way to handle it.
