### ISSUE TITLE
feature request: displaying linear folder tree as a single entry

### ISSUE THREAD

**Issue by Flygrounder** [stevearc/oil.nvim#311]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Consider the following folder structure
```
scala
└── com
    └── company
        └── program
```
If I want to get to program folder, I have to press `<CR>` 4 times. I want an optional feature that would display this subtree as a single line `scala/com/company/program` that will get me to `program` when pressing `<CR>`. `1<CR>` would get me to `scala`, `2<CR>` would get me to `com` etc.

### Provide background

Usually this feature won't make a difference, but when working on Scala projects, I always want this. I understand that tree view is out of scope, but this does not require one as this nested structure would still be a single line in a buffer. Also I understand that many users won't want this behavior, so it should be an opt-in feature.

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
Closing as not a good fit for oil. I understand the pain point, but I don't think the proposed solution is a good fit for this project. It would require another special case, which I generally would like to avoid, and it would actually be a fairly tricky case to code. Additionally, the UX of this has some problems. The simple case of jumping to the nested child is easy, but what if you want to rename the `company` directory? What if you want to add a file in the `com` directory? These operations may not be common, but suddenly they become much more difficult. Given the relatively small benefit, I don't think this is worth it.

**Comment by jdsee** [comment]
Hey @stevearc, I understand your reasoning but would like to revisit this, since I really miss this feature in Oil. Collapsing those linear structures would lead to a much smoother and quicker navigation.

I could imagine to simply toggle the collapsed view with a keybind. That would allow a workflow in which the collapsed view is enabled whenever I open Oil (opt-in ofc.) and whenever I want to modify anything inside a collapsed path I toggle to the default view and can make changes in the usual way. Ideally I'd like to jump into the directory under the cursor when toggling the view. 

Toggling the following would open `collapsed/` as usual Oil buffer.
```
/some/collapsed/file/path
           ^cursor
```

This approach gets rid of all the edge-cases I can think of. Personally I find this to fit well with the Oil philosophy. I have no idea if that would make the implementation any easier but I'd appreciate if you gave this idea another thought.

Thanks for considering and your great work on Oil!
