### ISSUE TITLE
hidden file and number

### ISSUE THREAD

**Issue by thevan96** [stevearc/oil.nvim#33]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I want to show hidden files as default, but in view_options `show_hidden = true` does not work.
I use ` :syntax off`, how to hide number(/00X) before the name file/folder?

**Comment by matu3ba** [comment]
`{ "stevearc/oil.nvim", config = function() require("oil").setup({view_options = { show_hidden = true, } }) end },` works for "I want to show hidden files as default, but in view_options show_hidden = true does not work.".

"I use  :syntax off, how to hide number(/00X) before the name file/folder?"

That can be seen as minor inconvenience, if one wants to do copy paste actions without the numbering:
```
/070 .editorconfig
/060 .gitignore
/072 20221021.log
/033 GIT.md
/062 README.md
/073 TODO
```
However, I dont see the big problem with block selection and deletion, since the dirent number is 0 prefixed to optimize such an action.

**Comment by thevan96** [comment]
I use vimplug, in view_options show_hidden = true does not work

**Comment by thevan96** [comment]
I have solved the problem, thank you very much for this interesting plugin.

**Comment by onelesd** [comment]
@thevan96 how did you solve the problem? hidden files/dirs do not show up for me.

```
  use({
    "stevearc/oil.nvim",
    config = function()
      require("oil").setup({
        view_options = {
          -- Show files and directories that start with "."
          show_hidden = true,
        },
      })
    end,
  })

vim.keymap.set(
  "n",
  "-",
  require("oil").open,
  { desc = "Open parent directory" }
)
```
