### ISSUE TITLE
Feature Request: Option to Disable LSP in Preview Window

### ISSUE THREAD

**Issue by kevintraver** [stevearc/oil.nvim#338]
It does not always make sense to have the LSP attached the preview window.

**Comment by tom-gora** [comment]
> It does not always make sense to have the LSP attached the preview window.

I'd argue it never makes sense, and would be nice to be set to off by default or completely throw away. Not only pointless overload of operations when scrolling through entries, but larger surface for potential breakage.  Had to disable some async lsp capabilities to get rid of the storm of errors as buffers get swapped faster than lsp is able to handle it and likely due to async nature of lsp operations, no amount of trying to prevent this, detach lsp or anything of sorts helped. Still getting spammed with lps progress indicators (notifications, fidget...) going crazy as I cycle entries. Would maybe make sense to prevent lsp from loading in the first place, or create a copy of buf with telescope syntax only to display as prev... But it is slightly outside of my capabilities for now, and I am quite swamped with school/work. It is not complaining - it's an honest opinion and some ideas added on top.

**Comment by kevintraver** [comment]
Fixed with #467. Thanks!
