### ISSUE TITLE
feature request: show only the path as the buffer's name

### ISSUE THREAD

**Issue by lourenci** [stevearc/oil.nvim#44]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

As a dirbuf/netrw long user, I love that their buffer name is only the name of the folder we are in.

Is that even possible to do on oil.nvim? Is it possible to remove the `oil://` prefix from the buffer name?

I often use a particular use case. I go to the folder and want to `:vimgrep` the files under that folder. If the buffer name is only the path, I could do `:vimgrep <pattern> <C-r>%` to fill with the folder path.

Anyway, thanks for this plugin. You addressed all the problems I had on dirbuf.

**Comment by stevearc** [comment]
The API includes the function [get_current_dir](https://github.com/stevearc/oil.nvim/#get_current_dir) which can be used to do things like this. I've also just added an action (`actions.open_cmdline_dir`) you can use to prepopulate the command line with the current directory as an argument. There's another action already to prepopulate the command line with the entry under the cursor (see `:help oil-actions` for a comprehensive list)

**Comment by stevearc** [comment]
That's totally fair, the interface is different and _does_ require remembering a mapping. Me not being able to remember my mappings was part of the reason I made this plugin in the first place :P 

At the moment I'm pretty tied to the idea of oil buffers having a specific url prefix. It provides some nice guarantees that make the code less buggy and easier to maintain. I may at some point remove that restriction to enable full drop-in replacement for netrw, but I don't expect to do that anytime soon.

As another potential workaround, you could try using an abbreviation to trim the leading `oil://` off of the buffer name:
```lua
vim.cmd.cabbr({ args = { "<expr>", "%", "&filetype == 'oil' ? bufname('%')[6:] : '%'" } })
```
Still not quite the same because instead of using `<c-r>` to get the contents of a register you're just typing the `%` directly, but it's at least closer to your workflow than the keymap.
