### ISSUE TITLE
feature request: No more prompt and instant save

### ISSUE THREAD

**Issue by nikitarevenco** [stevearc/oil.nvim#476]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would love to be able to not have to write `:w` when i want to save my changes, and rather have the changes be automatically saved :)

And also disable prompt for all actions, could this be an option?

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment]
Automatic saving is impossible because we have no way to know when your edits are complete. Moving a file requires you to delete, change directory, paste, then save. If we autosave at any point before you intend, you will experience data loss.

You can skip the action preview for simple operations with `skip_confirm_for_simple_edits = true`, but I have made a design decision to not provide a way to skip the preview for anything more complex. The reason is that I think safety and data integrity are paramount, and the added convenience 99% of the time of not needing to press the `y` key is outweighed by the 1% of the time when you realize that you accidentally deleted/moved/changed something that you did not intend to. That said, you _can_ skip the preview using the `oil.save()` lua API, so if you really must you can create a user command `:W` or `:Save` or make a keymap that calls the API directly and bypasses the preview.
