### ISSUE TITLE
Flickering when visiting parent directory

### ISSUE THREAD

**Issue by medwatt** [stevearc/oil.nvim#494]
I am trying out oil.nvim. It works fine except that when I am in a particular directory and visit the parent directory, I notice a momentary flicker, which is a bit irritating. This only happens the first time I visit the parent directory. If I go back to where I was and visit the parent directory, there's no flicker. I thought that this was due to the fact that I was visiting the directory for the first time. However, this is not the case because I don't notice the flicker when I go forward; it's only when I go backward. Any idea how to fix this?

**Comment by medwatt** [comment]
Looks like the developer doesn't care.

**Comment by Tronikelis** [comment]
> Looks like the developer doesn't care.

You are using another person's open source software, he does not have any obligation to do anything for you, this project is a gift which you can either use or not use, if you want to help, please give a simple reproducible config which we can test and check, and don't write "he don't care", because you are not entitled to anything

thank you

**Comment by medwatt** [comment]
@Tronikelis, yeah, that's why I removes it and used `mini.files` instead.
