### ISSUE TITLE
feature request: `default_file_explorer = true` should not disable netrw

### ISSUE THREAD

**Issue by rieje** [stevearc/oil.nvim#516]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It took me a while to realize oil.nvim's `default_file_explorer = true` disables netrw. From reading the description, this option should only prevent oil.nvim from being the defailt.

### Provide background

I would like to use oil.nvim as the default but still keep netrw to use exclusively for tree. Currently this doesn't seem possible, i.e. you can only choose one or the other.

Ideally oil.nvim supports a simplistic tree-style view (no additional fancy features needed), most people enjoy tree-style view for providing additional context and visualization that vim-vinegar-like explorers can't offer. 

### What is the significance of this feature?

strongly desired

**Comment by stevearc** [comment]
oil only disables netrw when `default_file_explorer = true`. 

https://github.com/stevearc/oil.nvim/blob/0472d9296ace2d57769eb3e022a918803f096ea4/lua/oil/init.lua#L1074-L1081

If you are seeing that oil is disabling netrw even when `default_file_explorer = false`, then please submit a bug report with a minimal init.lua that reproduces the issue.

**Comment by rieje** [comment]
Sorry, I meant `default_file_explorer = true` (updated title/post to correct this).

Basically, the request is that oil.nvim can remain the default file explorer without disabling netrw, since netrw still provides features oil.nvim doesn't, most importantly a simplistic tree-style view.

**Comment by stevearc** [comment]
If you want oil to be the default file explorer (oil opens when you `vim .` or `:edit .`), you have to disable netrw. Before I enforced this people had all kinds of weird state issues due to collisions with netrw. If you want to still use netrw, you'll just have to open oil with keymaps or the `:Oil` command. Honestly, I would recommend using something else. It's been a staple for a long time and respect for that, but there are better options now.
