### ISSUE TITLE
feature request: back and force to oil with bprev or ctrl-o

### ISSUE THREAD

**Issue by timsofteng** [stevearc/oil.nvim#59]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Would be cool to back and forth oil with some of vim commands.

### Provide background

It is so vimish way.

### Additional details

No it doesn't work.

**Comment by stevearc** [comment]
CTRL-i/o wasn't working because we were aggressively cleaning up oil buffers. I've tweaked that behavior so CTRL-i/o should work as expected now, but `:bprev`/`:bnext` only works for listed buffers. If you want to use those commands to jump through oil buffers you'll need to make sure the oil buffers are `set buflisted`.
