### ISSUE TITLE
feature request: save file with content into the clipboard on delete

### ISSUE THREAD

**Issue by MoronVV** [stevearc/oil.nvim#71]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

Hey, thanks for the great plugin!

Sometimes I need to move file from one dir to another. My desired actions (in oil window):
1. `dd` on file foo.txt with come content
2. go to dir bar
3. `p` to paste deleted file foo.txt

After pasting deleted file oil shows it, but it does not exists in os (and content in vim buffer is empty). Is there any way to make this logic works?

I can upload screencast with example, if needed.

### Provide background

I think, this is most intuitive and fast way to move files from one dir to another.

**Comment by stevearc** [comment]
All mutations are purely drafts until you `:w`. This is the only way to make certain operations (like moving files) work, and also provides you with a way to view the changes before they are made. If you want the file to exist, write the buffer! There's also an [API method](https://github.com/stevearc/oil.nvim/#saveopts) that you can call whenever you like.

**Comment by abenz1267** [comment]
Hijacking this since i regularly encounter following scenario:

1. DD file(s) in order to P somewhere else
2. create new folder
3. W in order to save new folder so I can go in there
4. ... but now the DD on the files i want to move will be written => can't paste files anymore => error

One thing i thought about just know is to edit the oil buffer this way:
```
filetomove.md
```

to 
```
subfolder/subfolder/filetomove.md
```

..but oil complains that filenames can't contain slashes. I'd actually expect oil to create the subfolders for me.

How do I work around this? Always having to remember to always create the desired directory structure first before DDing the file i want to copy&paste is kind of unintuitive.

Regards

**Comment by stevearc** [comment]
@abenz1267 skip step 3.
