### ISSUE TITLE
feature request: support for lazy plugin manager

### ISSUE THREAD

**Issue by horta** [stevearc/oil.nvim#75]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

If one configures it like

```
{
    "stevearc/oil.nvim",
    keys = { { "-", ":Oil<cr>", desc = "Open parent directory" } },
    config = function()
        require("oil").setup {}
    end
}
```

for use with [lazy](https://github.com/folke/lazy.nvim), you will notice that `vim .` and `:edit .` won't work as Oil has not been loaded yet.

If you force it to load immediately, like

```
{
    "stevearc/oil.nvim",
    keys = { { "-", ":Oil<cr>", desc = "Open parent directory" } },
    init = function()
        require("oil").setup {}
    end
}
```

then everything work as expected.

Is there an event that we can hook to load Oil for when `edit .`-like commands are executed?

Thanks for the amazing plugin!

**Comment by stevearc** [comment]
The trouble is that oil _may_ need to load as soon as you open vim (if you opened it with `vim .`), or it may not need to be opened until later. Internally, oil uses `BufAdd` to hijack directory buffers.
https://github.com/stevearc/oil.nvim/blob/3d3df74532eaea2b071da03079c3a4c8e4fe5aeb/lua/oil/init.lua#L837-L845

You could copy some of that logic and use it as a means to bootstrap oil. I also saw another example of someone using `BufNew` to trigger the loading. You could try copying what they did https://github.com/folke/lazy.nvim/issues/533

**Comment by horta** [comment]
That works flawlessly! Thanks @stevearc and @xulongwu4 =)

**Comment by EliasA5** [comment]
I used  ` {'stevearc/oil.nvim', lazy = false, config = function() require('oil').setup() end},` for loading with lazy and had no problems, it's a much simpler solution, can anyone confirm that it works for them?
if it works we can add it to the installation instruction in the `README.md`

**Comment by nyngwang** [comment]
@EliasA5 I think these are two different problems. By `lazy = false`, the plugin `oil.nvim` will be loaded even if a user never run `:Oil` to replace the current buffer with that of oil.nvim. This is not what "support for lazy plugin manager" in the title meant, since by providing `keys = ...` in the plugin spec for lazy.nvim, the post should mean that "if he never call `:Oil`, then this plugin will not even get loaded in the first place".

And to answer your question: yes it works, and it's what I'm using. You can even omit `lazy = false` since that's the default value. But all in all, it's not the same problem.
