### ISSUE TITLE
feature request: Support for Media File Previews

### ISSUE THREAD

**Issue by adelgado0723** [stevearc/oil.nvim#83]
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like to be able to see previews for image, video, pdf, svg, and other media files in the preview pane brought up with <C-p>. Perhaps by leveraging some of the tools used as dependencies of [telescope-media-files.nvim](https://github.com/nvim-telescope/telescope-media-files.nvim/blob/master/README.md).

### Provide background

I am trying to rename and move around media files in bulk and would really like to be able to do this using oil's 'editable file explorer buffer'. Currently, I'm using the [ranger](https://github.com/ranger/ranger) file browser, but it can be slow and buggy.

### Additional details

I've tried [telescope-media-files.nvim](https://github.com/nvim-telescope/telescope-media-files.nvim/blob/master/README.md), but would like this functionality in the file explorer instead of a fuzy finder.

**Comment by adelgado0723** [comment]
It would be my first time working on something like this, but I could take a stab at it if it's something people think is in-line with the vision for oil.

**Comment by stevearc** [comment]
I'm probably not going to work on this myself, but I would review a PR. If you're interested, this could potentially even be implemented as a separate plugin that any file explorer can hook into.

**Comment by adelarsq** [comment]
@adelgado0723 If you use wezterm I have created a plugin for this ([image_preview.nvim](https://github.com/adelarsq/image_preview.nvim)). Using oil and pressing <leader>p shows like this:

![image](https://github.com/stevearc/oil.nvim/assets/430272/0ec12e91-2ae5-4a71-86f1-59772896a260)

@stevearc It's there any way to override select action? So would be possible to open image files with <cr> instead of <leader>p (default mapping for my plugin)

**Comment by stevearc** [comment]
It looks like [image.nvim](https://github.com/3rd/image.nvim) released a new version that does this for images!

I'm going to close this issue now because even though there isn't an established solution for pdf/video, it's outside the scope of oil. This functionality is best handled by other plugins.
